version: '3.8'

services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
      target: development
    command: pnpm start:debug
    depends_on:
      - database
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    command: pnpm start
    ports:
      - '3001:3001'
    links:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  database:
    container_name: database
    image: postgres:latest
    restart: always
    env_file:
      - .env.db
    ports:
      - '5432:5432'



